grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate uiTest "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	commands+=Command*;
	
Command:
	(Open | GoOn | Fill | Select | Click | Verify) ';' ;
Open:
	"open(" program=ID ")" ;
GoOn:
	"goOn(" adress=ID ")" ;
Fill:
	"fill(" fieldName=ID ',' fieldValue=ID ")" ;
Select:
	"select(" fieldName=ID ")" ;
Click:
	"click(" fieldName=ID ")" ;
Verify:
	"verify(" link=ID ")" ;
	