/**
 * generated by Xtext 2.10.0
 */
package org.emn.ui.contentassist;

import org.emn.ui.contentassist.AbstractUiTestProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class UiTestProposalProvider extends AbstractUiTestProposalProvider {
}
