/**
 * generated by Xtext 2.10.0
 */
package org.emn.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.emn.ui.AbstractUiTestUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class UiTestUiModule extends AbstractUiTestUiModule {
  public UiTestUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
