/*
 * generated by Xtext 2.10.0
 */
package org.emn.ui.tests;

import com.google.inject.Injector;
import emn.fil.a3.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class UiTestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.emn.UiTest");
	}

}
