/*
 * generated by Xtext 2.10.0
 */
package org.emn


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UiTestStandaloneSetup extends UiTestStandaloneSetupGenerated {

	def static void doSetup() {
		new UiTestStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
