/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.uiTest;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Go On</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.uiTest.GoOn#getAdress <em>Adress</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.uiTest.UiTestPackage#getGoOn()
 * @model
 * @generated
 */
public interface GoOn extends Command
{
  /**
   * Returns the value of the '<em><b>Adress</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Adress</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Adress</em>' attribute.
   * @see #setAdress(String)
   * @see org.xtext.example.mydsl.uiTest.UiTestPackage#getGoOn_Adress()
   * @model
   * @generated
   */
  String getAdress();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.uiTest.GoOn#getAdress <em>Adress</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Adress</em>' attribute.
   * @see #getAdress()
   * @generated
   */
  void setAdress(String value);

} // GoOn
