/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.uiTest;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Open</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.uiTest.Open#getProgram <em>Program</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.uiTest.UiTestPackage#getOpen()
 * @model
 * @generated
 */
public interface Open extends Command
{
  /**
   * Returns the value of the '<em><b>Program</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Program</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Program</em>' attribute.
   * @see #setProgram(String)
   * @see org.xtext.example.mydsl.uiTest.UiTestPackage#getOpen_Program()
   * @model
   * @generated
   */
  String getProgram();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.uiTest.Open#getProgram <em>Program</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Program</em>' attribute.
   * @see #getProgram()
   * @generated
   */
  void setProgram(String value);

} // Open
