/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.uiTest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.uiTest.UiTestFactory
 * @model kind="package"
 * @generated
 */
public interface UiTestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "uiTest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "uiTest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UiTestPackage eINSTANCE = org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.ModelImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.CommandImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.OpenImpl <em>Open</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.OpenImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getOpen()
   * @generated
   */
  int OPEN = 2;

  /**
   * The feature id for the '<em><b>Program</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN__PROGRAM = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Open</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.GoOnImpl <em>Go On</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.GoOnImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getGoOn()
   * @generated
   */
  int GO_ON = 3;

  /**
   * The feature id for the '<em><b>Adress</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_ON__ADRESS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Go On</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GO_ON_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.FillImpl <em>Fill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.FillImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getFill()
   * @generated
   */
  int FILL = 4;

  /**
   * The feature id for the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__FIELD_NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Field Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__FIELD_VALUE = COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.SelectImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 5;

  /**
   * The feature id for the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__FIELD_NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.ClickImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getClick()
   * @generated
   */
  int CLICK = 6;

  /**
   * The feature id for the '<em><b>Field Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__FIELD_NAME = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.uiTest.impl.VerifyImpl <em>Verify</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.uiTest.impl.VerifyImpl
   * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getVerify()
   * @generated
   */
  int VERIFY = 7;

  /**
   * The feature id for the '<em><b>Link</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY__LINK = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Verify</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.uiTest.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.uiTest.Model#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.mydsl.uiTest.Model#getCommands()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Commands();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.mydsl.uiTest.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.Open <em>Open</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open</em>'.
   * @see org.xtext.example.mydsl.uiTest.Open
   * @generated
   */
  EClass getOpen();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.uiTest.Open#getProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Program</em>'.
   * @see org.xtext.example.mydsl.uiTest.Open#getProgram()
   * @see #getOpen()
   * @generated
   */
  EAttribute getOpen_Program();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.GoOn <em>Go On</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Go On</em>'.
   * @see org.xtext.example.mydsl.uiTest.GoOn
   * @generated
   */
  EClass getGoOn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.uiTest.GoOn#getAdress <em>Adress</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Adress</em>'.
   * @see org.xtext.example.mydsl.uiTest.GoOn#getAdress()
   * @see #getGoOn()
   * @generated
   */
  EAttribute getGoOn_Adress();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.Fill <em>Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill</em>'.
   * @see org.xtext.example.mydsl.uiTest.Fill
   * @generated
   */
  EClass getFill();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.uiTest.Fill#getFieldName <em>Field Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Name</em>'.
   * @see org.xtext.example.mydsl.uiTest.Fill#getFieldName()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_FieldName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.uiTest.Fill#getFieldValue <em>Field Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Value</em>'.
   * @see org.xtext.example.mydsl.uiTest.Fill#getFieldValue()
   * @see #getFill()
   * @generated
   */
  EAttribute getFill_FieldValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.xtext.example.mydsl.uiTest.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.uiTest.Select#getFieldName <em>Field Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Name</em>'.
   * @see org.xtext.example.mydsl.uiTest.Select#getFieldName()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_FieldName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.example.mydsl.uiTest.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.uiTest.Click#getFieldName <em>Field Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field Name</em>'.
   * @see org.xtext.example.mydsl.uiTest.Click#getFieldName()
   * @see #getClick()
   * @generated
   */
  EAttribute getClick_FieldName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.uiTest.Verify <em>Verify</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify</em>'.
   * @see org.xtext.example.mydsl.uiTest.Verify
   * @generated
   */
  EClass getVerify();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.uiTest.Verify#getLink <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link</em>'.
   * @see org.xtext.example.mydsl.uiTest.Verify#getLink()
   * @see #getVerify()
   * @generated
   */
  EAttribute getVerify_Link();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UiTestFactory getUiTestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.ModelImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMMANDS = eINSTANCE.getModel_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.CommandImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.OpenImpl <em>Open</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.OpenImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getOpen()
     * @generated
     */
    EClass OPEN = eINSTANCE.getOpen();

    /**
     * The meta object literal for the '<em><b>Program</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN__PROGRAM = eINSTANCE.getOpen_Program();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.GoOnImpl <em>Go On</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.GoOnImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getGoOn()
     * @generated
     */
    EClass GO_ON = eINSTANCE.getGoOn();

    /**
     * The meta object literal for the '<em><b>Adress</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GO_ON__ADRESS = eINSTANCE.getGoOn_Adress();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.FillImpl <em>Fill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.FillImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getFill()
     * @generated
     */
    EClass FILL = eINSTANCE.getFill();

    /**
     * The meta object literal for the '<em><b>Field Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__FIELD_NAME = eINSTANCE.getFill_FieldName();

    /**
     * The meta object literal for the '<em><b>Field Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL__FIELD_VALUE = eINSTANCE.getFill_FieldValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.SelectImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Field Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__FIELD_NAME = eINSTANCE.getSelect_FieldName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.ClickImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Field Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK__FIELD_NAME = eINSTANCE.getClick_FieldName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.uiTest.impl.VerifyImpl <em>Verify</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.uiTest.impl.VerifyImpl
     * @see org.xtext.example.mydsl.uiTest.impl.UiTestPackageImpl#getVerify()
     * @generated
     */
    EClass VERIFY = eINSTANCE.getVerify();

    /**
     * The meta object literal for the '<em><b>Link</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERIFY__LINK = eINSTANCE.getVerify_Link();

  }

} //UiTestPackage
