/**
 * generated by Xtext 2.10.0
 */
package org.emn.validation;

import org.emn.validation.AbstractUiTestValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class UiTestValidator extends AbstractUiTestValidator {
}
