/**
 * generated by Xtext 2.10.0
 */
package org.emn;

import org.emn.AbstractUiTestRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class UiTestRuntimeModule extends AbstractUiTestRuntimeModule {
}
