/**
 * generated by Xtext 2.10.0
 */
package org.emn.uiTest.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.emn.uiTest.ID;
import org.emn.uiTest.UiTestFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>ID</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class IDTest extends TestCase {

	/**
	 * The fixture for this ID test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ID fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(IDTest.class);
	}

	/**
	 * Constructs a new ID test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IDTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this ID test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(ID fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this ID test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ID getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(UiTestFactory.eINSTANCE.createID());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //IDTest
