/**
 * generated by Xtext 2.10.0
 */
package org.emn.uiTest.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.emn.uiTest.UiTest;
import org.emn.uiTest.UiTestFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Ui Test</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class UiTestTest extends TestCase {

	/**
	 * The fixture for this Ui Test test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UiTest fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(UiTestTest.class);
	}

	/**
	 * Constructs a new Ui Test test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UiTestTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Ui Test test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(UiTest fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Ui Test test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UiTest getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(UiTestFactory.eINSTANCE.createUiTest());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //UiTestTest
