/**
 * generated by Xtext 2.10.0
 */
package org.emn.uiTest.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.emn.uiTest.UiTestFactory;
import org.emn.uiTest.VariableDefinition;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Variable Definition</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class VariableDefinitionTest extends TestCase {

	/**
	 * The fixture for this Variable Definition test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableDefinition fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(VariableDefinitionTest.class);
	}

	/**
	 * Constructs a new Variable Definition test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public VariableDefinitionTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Variable Definition test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(VariableDefinition fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Variable Definition test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected VariableDefinition getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(UiTestFactory.eINSTANCE.createVariableDefinition());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //VariableDefinitionTest
