/**
 * generated by Xtext 2.10.0
 */
package org.emn.uiTest.tests;

import junit.textui.TestRunner;

import org.emn.uiTest.UiTestFactory;
import org.emn.uiTest.Verify;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Verify</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class VerifyTest extends CommandTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(VerifyTest.class);
	}

	/**
	 * Constructs a new Verify test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public VerifyTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Verify test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Verify getFixture() {
		return (Verify)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(UiTestFactory.eINSTANCE.createVerify());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //VerifyTest
