/*
 * generated by Xtext 2.10.0
 */
package org.emn.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractUiTestScopeProvider extends DelegatingScopeProvider {
}
