/**
 * generated by Xtext 2.10.0
 */
package org.emn.uiTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.emn.uiTest.UiTestPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
} // Command
